### PR TITLE
make rowsToAmount in QueryUtilities public to allow for re-use (2nd attempt)

### PR DESCRIPTION
**Pull request by philippkueng**
re-open due to @roastario's request https://github.com/corda/token-sdk/pull/51

### CODE REVIEW

**Comment by roger3cev** [comment]
@philippkueng  This is _supposed_ to be a private function. What do you need to expose it for? Or rather... What other public functions are missing? Cheers

**Comment by philippkueng** [comment]
@roger3cev that was my question as part of PR https://github.com/corda/token-sdk/pull/51 (the same diff) - we're needing it because we'd like to create our own account specific queries and would like to re-use your base queries, enhance the criteria list and then use `rowsToAmount` as if we'd be just using your queries as part of the token-sdk.

**Comment by roger3cev** [comment]
OK great. So what specific queries do you need? We can add them to the project?

**Comment by roger3cev** [comment]
The thing is... I'm reluctant to expose loads of detail in the SDK because I need the freedom to change implementation in the future. Exposing this will lead to being quite limited on what we can do in the future. I'd far rather add public APIs which handle your needs.

**Comment by philippkueng** [comment]
I understand your concern and in some respects given that token-sdk isn't 1.0 stable yet, we currently consider all of it changeable anyway. Will attempt to commit some of the queries back to the token-sdk and potentially account-sdk in the future (@nimmaj will have more details on) - and if you feel like you have to change it, then please do that. In that case we can still decide if we'd like to adapt or then copy your previous version into our code.

**Comment by roger3cev** [comment]
@philippkueng Thanks for understanding! Will approve this for now so it unblocks you. Cheers

**Pull request merged**
