### PR TITLE
Change Sate -> State typo in filename

### PR DESCRIPTION
**Pull request by olliegilbey**
Fixes Typo

### CODE REVIEW

**Comment by davidawad** [comment]
This PR exists to fix issue #177 (https://github.com/corda/token-sdk/issues/177).

**Review by davidawad — COMMENTED** [review]
LGTM 👍

**Review by r3domfox — APPROVED** [review]
As the change is only to the file name, and not the class name, it should not break any dependencies.

**Comment by olliegilbey** [comment]
@r3domfox @roastario , hey team, do either of you know what might be going wrong with the build here - something on gradle. If I should re-push, let me know.
We are quite keen to know more about the PR and build process on these repos. Thanks!

**Pull request closed without merging**
