### PR TITLE
Added contract tests for non fungible tokens.

### PR DESCRIPTION
**Pull request by roger3cev**
Moved fungible and non fungible token schemas into an internal package. 
Updated some kdocs for clarity. 
Added a new infix withNewHolder function. 
Non-fungible token contract now checks that linear ID doesn't change. 
Fixed some usability issues with the non-fungible token contract. 
Added issue and redeem tests for non fungible token contract. 
Moved common contract test stuff into an abstract class used by the other test classes. 
Fixed an error in the README. 
Moved the internal package to the workflows package as it also contained schemas as well as flows.

### CODE REVIEW

**Comment by roastario** [comment]
build

**Comment by roger3cev** [comment]
build

**Comment by roastario** [comment]
build

**Comment by roastario** [comment]
build

**Comment by roastario** [comment]
build

**Comment by roastario** [comment]
build

**Comment by roastario** [comment]
build

**Pull request merged**
