### PR TITLE
Minor Edit: Parallelise the IssueToken and EvolvableToken utility methods

### PR DESCRIPTION
**Pull request by illoyd**
Make the composable utility methods parallel:

* addIssueToken signature changes
* move EvolvableToken utilities into evolvable module

---
_I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org)._

### CODE REVIEW

**Comment by roger3cev** [comment]
@roastario looks like the CI is still broken!

**Comment by roastario** [comment]
please run tests

**Comment by roastario** [comment]
build

**Comment by roastario** [comment]
build

**Comment by roger3cev** [comment]
Force merging as TC status is no longer relevant. Thanks @illoyd !

**Comment by roastario** [comment]
Can one of the admins verify this patch?

**Pull request merged**
